POST http://127.0.0.1:4443/add_note HTTP/1.1
content-type: application/json

{
    "content": "hello world",
    "created_at": "2022/4/29 00:59:00",
    "updated_at": "2022/4/29 00:59:00"
}

###
POST http://127.0.0.1:4443/add_note HTTP/1.1
content-type: application/json
token: 3.1415926pi

{
    "content": "hello world token test"
}


###
get http://127.0.0.1:4443/get_all_notes HTTP/1.1
content-type: application/json